service: spext-app

runtime: nodejs16

instance_class: B2

env: standard

env_variables:
  ADAPTER: mongodb+srv://node:w3i3zJs4LQbfXLSD@spext.2r6nh.mongodb.net/spext?retryWrites=true&w=majority
  S3_URI: storage.googleapis.com
  S3_ACCESS_KEY: GOOG1E75WTNXF3BRCYY5X6ALURQSBXSTOCOO7ODU7KFXMGYEF6ZOGC3XMY3UY
  S3_SECRET_KEY: BsMlwab9DBOSVcW8n/DQnjz9+/v+WAziFthJHXr0
  S3_BUCKET: spext
  S3_REGION: asia-south1

basic_scaling:
  max_instances: 1
  idle_timeout: 10m