service: spext-app

runtime: nodejs16

instance_class: B2

env: standard

env_variables:
  ADAPTER: mongodb+srv://node:w3i3zJs4LQbfXLSD@spext.2r6nh.mongodb.net/spext?retryWrites=true&w=majority
  S3_URI: storage.googleapis.com
  S3_ACCESS_KEY: GOOG1ETTBFXU2NF6M3PIVESBBLBDSZZGTJY6AA25A24LAXE7NAGAP6YMGP3SI
  S3_SECRET_KEY: vRpIp5SjK95lV58CjlBgKU4vmXB7cMVmaN/b1RSq
  S3_BUCKET: spext
  S3_REGION: asia-south1

basic_scaling:
  max_instances: 1
  idle_timeout: 10m