version: '3.8'

networks:
    micros:
        driver: overlay
        attachable: true
    db:
        driver: overlay
        attachable: true

services:
    app:
        build: .
        image: spext_app:dev
        command: npm run dev
        ports:
            - 3000:3000
        environment:
            NODE_ENV: development
            ADAPTER: mongodb://mongodb:27017/spext
            # ADAPTER: mongodb+srv://appengine:EkamMJZj4pzTOxMR@production.z8a5n.mongodb.net/tabpro?retryWrites=true&w=majority
            LOGLEVEL: debug
            S3_URI: storage.googleapis.com
            S3_ACCESS_KEY: GOOG1ETTBFXU2NF6M3PIVESBBLBDSZZGTJY6AA25A24LAXE7NAGAP6YMGP3SI
            S3_SECRET_KEY: vRpIp5SjK95lV58CjlBgKU4vmXB7cMVmaN/b1RSq
            S3_BUCKET: spext
            S3_REGION: asia-south1
        volumes:
            - .:/app
        networks:
            - micros
            - db

    mongodb:
        image: bitnami/mongodb:4.4
        ports:
            - 27017:27017
        volumes:
            - ./data/mongodb:/bitnami/mongodb
        networks:
            - db