name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploys to GCP App Engine
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          workload_identity_provider: projects/551869806113/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: my-service-account@tabeazy.iam.gserviceaccount.com


      - id: deploy
        name: GCP App Engine Deploy
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          version: main
      
      - name: URL
        run: 'echo ${{ steps.deploy.outputs.url }}'
