name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploys to GCP App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/759067194003/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: spext-service@hariaakash.iam.gserviceaccount.com


      - id: deploy
        name: GCP App Engine Deploy
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          version: main
      
      - name: URL
        run: 'echo ${{ steps.deploy.outputs.url }}'